# Even Fibonacci numbers
# Problem 2 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


max_value = 4000000
fib = [1, 2]
value = max(fib)
while value < max_value:
	value = fib[-2] + fib[-1]
	fib.append(value)

fib_even = [x for x in fib[:-1] if x%2==0]

print('Sum of even terms of Fibonacci sequence whose values do not exceed {}: {}'.format(max_value, sum(fib_even)))

# Sum of even terms of Fibonacci sequence whose values do not exceed 4000000: 4613732